apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    name: login-app-service
    app: login-application
spec:
  #type: LoadBalancer  -> This Option will automatically get an IP from GKE
  type: NodePort 
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30914
  selector:
    name: app-pod
    app: login-application
